name: publish
on:
  push:
    branches:
     - master
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Get the TAG
        id: get_tag
        run: echo ::set-output name=TAG::$(git show-ref --tags | grep ${{ github.sha }} | cut -d / -f 3)
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      - 
        - name: Update resources
          uses: test-room-7/action-update-file@v1
          run: echo ${{ steps.get_tag.outputs.TAG }}; echo steps.get_tag.outputs.TAG;
          with:
              file-path: ../../VERSION
              commit-msg: Update VERSION
              github-token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: release_binaries
          path: ./dist
