# name: Release

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Tag
#         if: ${{ github.event_name != 'pull_request' }}
#         uses: K-Phoen/semver-release-action@master
#         with:
#           release_branch: master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
