name: Version

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get tag
        id: get_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - 
        name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ github.workspace }}/VERSION
          write-mode: overwrite
          contents: |
            ${{ steps.get_tag.outputs.tag }}
      - 
        name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions'
      