name: Version

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: 'VERSION'
          placeholder: '${VERSION}'
      