name: Version

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - 
        name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ github.workspace }}/VERSION
          write-mode: overwrite
          contents: |
            $GITHUB_REF_NAME
      - 
        name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions'
      