name: Version

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get the TAG
        id: get_tag
        run: echo ::set-output name=TAG::$(git show-ref --tags | grep ${{ github.sha }} | cut -d / -f 3)
      - 
        name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ github.workspace }}/VERSION
          write-mode: overwrite
          contents: |
            $GITHUB_REF_NAME
      - 
        name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions'
      